name: lint
on: [pull_request]
jobs:
  linting:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint typescript
      - name: Lint
        run: npx eslint .
