name: test
on: [pull_request]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # TODO: import mocha and chai??
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install
        run: npm install
      - name: Test
        run: npm run test
